name: Auto Create Pull Request

on:
  push:
    branches:
      - feature/*  # Runs when a branch prefixed with "feature/" is pushed

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Commit Message
        id: commit_msg
        run: |
          echo "TITLE=$(git log -1 --pretty=%s)" >> $GITHUB_ENV
          echo "BODY=$(git log -1 --pretty=%b)" >> $GITHUB_ENV

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          branch: ${{ github.ref_name }}
          base: main
          title: "${{ env.TITLE }}"
          body: "${{ env.BODY }}"
          labels: |
            automated pr
