name: Auto Create Pull Request

on:
  push:
    branches:
      - feature/*  # Runs when a branch prefixed with "feature/" is pushed

jobs:
  createPullRequest:
    permissions: write-all
    runs-on: ubuntu-latest
    name: Automatic Pull Request

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures full commit history

      - name: Get Commit Message
        id: commit_msg
        run: |
          echo "TITLE=$(git log -1 --pretty=%s)" >> $GITHUB_ENV
          echo "BODY=$(git log -1 --pretty=%b)" >> $GITHUB_ENV

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          branch: ${{ github.ref_name }}
          title: "${{ env.TITLE }}"
          body: "${{ env.BODY }}"
          labels: |
            automated pr
          draft: false

